---
title: "US Top Income Shares 1913-2018 (Data)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 [`TabFig2015prel.xls`](http://eml.berkeley.edu//~saez/TabFig2017prel.xls)` 를 손봐서 불러들인 것이다. 

### xlsx

```{r, read.xlsx, message = FALSE, echo = FALSE, results = 'hide', eval = FALSE}
options(digits = 3)
library(xlsx)
US_top_income_shares_18 <- 
  read.xlsx("../data/TabFig2018prel.xlsx", 
            sheetIndex = 9, 
            sheetName = "Table A3", 
            startRow = 6, 
            endRow = 111, 
            colIndex = c(1:7, 9:13), 
            colClasses = c("integer", rep("numeric", 12)), 
            header = FALSE)
v_names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
names(US_top_income_shares_18) <- v_names
US_top_income_shares_18[106, 1] <- 2018L
str(US_top_income_shares_18)
```

### openxlsx

```{r, openxlsx, message = FALSE, echo = FALSE, results = 'hide', eval = FALSE}
library(openxlsx)
v_names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
US_top_income_shares_18 <-
  openxlsx::read.xlsx("../data/TabFig2018prel.xlsx",
                      sheet = "Table A3",    #> sheet = 9, not working, sheet = 10
                      colNames = FALSE,
                      cols = c(1:7, 9:13),
                      rows = 6:111)
names(US_top_income_shares_18) <- v_names
US_top_income_shares_18[106, 1] <- 2018L
str(US_top_income_shares_18)
class(US_top_income_shares_18[, 1]) <- "integer"
```

### readxl

```{r, readxl, message = FALSE, echo = FALSE, results = 'hide', eval = TRUE}
library(readxl)
library(magrittr)
v_names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
US_top_income_shares_18 <-
  readxl::read_excel("../data/TabFig2018prel.xlsx",
                     sheet = "Table A3",
#                     sheet = 9, #> openxlsx 와 같은 문제점 발생
                     range = "A6:M111",
#                    range = "Table A3!A6:M111",
                     col_names = FALSE)
US_top_income_shares_18 <- US_top_income_shares_18[-8]
names(US_top_income_shares_18) <- v_names
US_top_income_shares_18[106, 1] <- 2018L
str(US_top_income_shares_18)
US_top_income_shares_18 %<>% 
  data.frame
class(US_top_income_shares_18$Year) <- "integer"
```


<!--작업을 마친 자료파일은 `US_top_income_shares_18`이며, 이 자료의 구조와 앞의 몇 열의 값은 다음과 같다.-->

```{r, data structure, echo = FALSE}
library(knitr)
kable(format(US_top_income_shares_18, digits = 1, nsmall = 1))
```

## Save Data

```{r, save.image}
saveRDS(US_top_income_shares_18, file = "./US_top_income.RDS")
save.image(file = "US_top_income_shares_2018.RData")
```