---
title: "Income Inequality vs Index of Health and Social Problems"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

### Data Reading

Equality Trust에서 기부금을 받고 제공하는 두 종류의 자료 중 23개 국가의 각종 지표를 비교한 자료에 [World Bank에서 발표하는 GDP자료](https://en.wikipedia_org/wiki/List_of_countries_by_GDP_(PPP)_per_capita)를 추가한 자료를 data 단계에서 읽어들이고 필요한 부분만 정리한 `RData`파일을 읽어들이면,

```{r, data with GDP}
library(knitr)
load("Inequality_Index_HS.RData")
str(data_21)
options(width = 132)
```

### Plots

### Barplots for Income Inequalities

```{r, barplot of 5th ratios 1st, fig.width = 12, fig.height = 6}
# par(mai = c(2.0, 0.8, 0.8, 0.4) + 0.2)
(fifth <- data_21$Income_inequality)
barplot(fifth)
```

```{r, barplot of 5th ratios 2nd, fig.width = 12, fig.height = 6}
(Country <- data_21$Country)
barplot(fifth, names.arg = Country)
```

```{r, barplot of 5th ratios 3rd, fig.width = 12, fig.height = 6}
(o_fifth <- order(fifth))
data.frame(Country, fifth, o_fifth, fifth[o_fifth], Country[o_fifth])
rev_o_fifth <- order(fifth, decreasing = TRUE)
data.frame(Country, fifth, o_fifth, rev_o_fifth, fifth[rev_o_fifth], Country[rev_o_fifth])
barplot(fifth[o_fifth])
```

```{r, barplot of 5th ratios 4th, fig.width = 12, fig.height = 6}
barplot(fifth[o_fifth], names.arg = Country[o_fifth])
```

```{r, colors in rainbow}
N <- nrow(data_21)
par(mfrow = c(1, 2))
pie(rep(1, N), radius = 1.0, col = rainbow(N, start = 1/6, end = 1))
pie(rep(1, N), radius = 1.0, col = rainbow(N, start = 0, end = 1/6))
par(mfrow = c(1, 1))
```

```{r, barplot of 5th ratios 5th, fig.width = 12, fig.height = 6}
barplot(fifth[o_fifth], names.arg = Country[o_fifth],  col = rainbow(N, start = 1/6, end = 1))
```

```{r, barplot of 5th ratios 6th, fig.width = 12, fig.height = 6}
barplot(fifth[o_fifth], names.arg = Country[o_fifth],  col = rainbow(N, start = 1/6, end = 1), las = 2)
```

```{r, barplot of 5th ratios text annotation, fig.width = 12, fig.height = 8}
b_fifth <- barplot(fifth[o_fifth], names.arg = Country[o_fifth], col = rainbow(N, start = 1/6, end = 1), ylim = c(0, 10), xpd = FALSE, las = 2)
text(x = b_fifth, y = fifth[o_fifth] + 0.3, labels = format(fifth[o_fifth], digits = 3))
# text(x = b_fifth, y = fifth[o_fifth], labels = format(fifth[o_fifth], digits = 3))
# text(x = b_fifth[c(1, 11, 21)], y = fifth[o_fifth][c(1, 11, 21)] + 0.3, labels = format(fifth[o_fifth][c(1, 11, 21)], digits = 3))
title(main = "Fifth Ratios of Selected Countries", cex.main = 2)
```

<!--
```{r, save}
save.image(file = "Inequality_Index_HS_add.RData")
```
-->









